version: '3.5'
services:
  nubo-rsyslog:
    image: nubosoftware/nubo-rsyslog:${RSYSLOG_TAG}
    container_name: nubo-rsyslog
    hostname: nubo-rsyslog
    restart: always
    volumes:
      - type: bind
        source: ./log
        target: /opt/nubo-rsyslog/log
      - type: bind
        source: ./nubo-rsyslog/conf
        target: /opt/nubo-rsyslog/conf
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
    expose:
      - "5514/udp"
    networks:
      - net_fe
      - net_ps
      - net_db
    depends_on:
      - nubo-mysql
  nubo-registry:
    image: registry:2
    container_name: nubo-registry
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /cert/server.cert
      REGISTRY_HTTP_TLS_KEY: /cert/server.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /cert/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - type: bind
        source: ./registry
        target: /var/lib/registry
      - type: bind
        source: ./cert
        target: /cert
    ports:
      - "5000:5000"
  nubo-mysql:
    image: ubuntu/mysql:${MYSQL_TAG}
    container_name: nubo-mysql
    hostname: nubo-mysql
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /var/lib/mysql-init
    networks:
      - net_db
  nubo-redis:
    image: redis:${REDIS_TAG}
    container_name: nubo-redis
    hostname: nubo-redis
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
    command: redis-server
    networks:
      - net_db

  nubo-management:
    image: nubosoftware/nubomanagement:${MANAGEMENT_TAG}
    container_name: nubo-management
    hostname: nubo-management
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - type: bind
        source: ./nubomanagement/conf
        target: /opt/nubomanagement/conf
      - type: bind
        source: ./nubomanagement/locales
        target: /opt/nubomanagement/locales
      - type: bind
        source: ./nubomanagement/docker_apps
        target: /opt/nubomanagement/docker_apps
      - type: bind
        source: /opt/nubo/nfs/homes
        target: /opt/nubo/nfs/homes
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./common/etc/rsyslog.d
        target: /etc/rsyslog.d
    networks:
      - net_fe
      - net_db
      - net_ps
    depends_on:
      - nubo-mysql
      - nubo-redis
      - nubo-rsyslog

  nubo-frontend:
    image: nubosoftware/nubofrontend:${FRONTEND_TAG}
    container_name: nubo-frontend
    hostname: nubo-frontend
    restart: always
    deploy:
      mode: global
    volumes:
      - type: bind
        source: ./frontend/conf
        target: /opt/nubomanagement-public/conf
      - type: bind
        source: ./cert
        target: /opt/cert
      - type: bind
        source: ./common/etc/rsyslog.d
        target: /etc/rsyslog.d
    ports:
      - "80:80"
      - "443:443"
      - "6080:6080"
      - "6443:6443"
    networks:
      - net_fe
    depends_on:
      - nubo-management

  nubo-gateway:
    image: nubosoftware/gateway:${GATEWAY_TAG}
    container_name: nubo-gateway
    hostname: nubo-gateway
    restart: always
    deploy:
      mode: global
    volumes:
    - type: bind
      source: ./gateway/conf
      target: /opt/nubogateway/conf
    - type: bind
      source: ./cert
      target: /opt/cert
    - type: bind
      source: ./common/etc/rsyslog.d
      target: /etc/rsyslog.d
    networks:
      - net_fe
      - net_sess
    depends_on:
      - nubo-management
  nubo-ps:
    image: nubosoftware/nuboplatformserver:${PS_TAG}
    container_name: nubo-ps
    hostname: nubo-ps
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role!=manager"
    networks:
      - net_ps
    expose:
      - "3334"
    volumes:
      - type: bind
        source: ./platform_server/conf
        target: /opt/platform_server/conf
      - type: bind
        source: /opt/nubo/nfs/homes
        target: /opt/nubo/nfs/homes
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./common/etc/rsyslog.d
        target: /etc/rsyslog.d
    depends_on:
      - nubo-rsyslog

networks:
  net_db:
   name: net_db
  net_ps:
   name: net_ps
  net_fe:
    name: net_fe
  net_sess:
    name: net_sess
    attachable: true
